language: python

before_install:
    - pip install -U pip
    - pip install -U pytest
    - pip install -U pycodestyle
    - pip install -U matplotlib

script:
    - python test_get_tissue_samples.py
    - bash test_get_tissue_samples.sh
    - python test_get_gene_counts.py
    - bash test_get_gene_counts.sh
    - python test_box.py
    - bash test_box.sh